name: Run SimpleWikiBot
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

  workflow_dispatch:
    # Allows manual execution of the workflow via GitHub Actions

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      env:
        WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
        WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
      run: |
        echo "Starting SimpleWikiBot..."
        python vip_bot.py
